name: esay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_code_scanner_plus: ^2.0.10+1
  
  postgres: ^2.6.1
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  location: ^5.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  flutter_foreground_task: ^6.0.0
  mobile_scanner: ^6.0.7
  flutter_keyboard_visibility: ^6.0.0
  excel: ^2.0.0-null-safety-3
  path_provider: ^2.0.11
  open_file: ^3.2.1
  bcrypt: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png